services:
  - type: worker
    name: rekber-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL
        sync: false
      - key: BOT_ID
        sync: false
